
ifneq ($(shell which docker-compose 2>/dev/null),)
    DOCKER_COMPOSE := docker-compose
else
    DOCKER_COMPOSE := docker compose
endif

install:
	$(DOCKER_COMPOSE) up -d

remove:
	@chmod +x confirm_remove.sh
	@./confirm_remove.sh

start:
	$(DOCKER_COMPOSE) start
startAndBuild: 
	$(DOCKER_COMPOSE) up -d --build

stop:
	$(DOCKER_COMPOSE) stop

update:
	# Calls the LLM update script
	chmod +x update_ollama_models.sh
	@./update_ollama_models.sh
	@git pull
	$(DOCKER_COMPOSE) down
	# Make sure the ollama-webui container is stopped before rebuilding
	@docker stop open-webui || true

# --- Added by Copilot (OpenAI): Local infra helpers for OpenTofu ---
.PHONY: infra-up infra-down infra-env

infra-up:
	@echo "[infra] Applying OpenTofu stack (LocalStack + DynamoDB Local + queues + table)"
	cd infra/opentofu && tofu init && tofu apply -auto-approve
	@echo "[infra] Writing llm-gateway/.env.localstack"
	@echo "# Generated by Makefile" > llm-gateway/.env.localstack
	@echo AWS_REGION=us-east-1 >> llm-gateway/.env.localstack
	@echo AWS_ACCESS_KEY_ID=test >> llm-gateway/.env.localstack
	@echo AWS_SECRET_ACCESS_KEY=test >> llm-gateway/.env.localstack
	@echo SQS_ENDPOINT_URL=http://localhost:4566 >> llm-gateway/.env.localstack
	@echo DYNAMODB_ENDPOINT_URL=http://localhost:8000 >> llm-gateway/.env.localstack
	@echo DDB_TABLE=Conversations >> llm-gateway/.env.localstack
	@echo SQS_QUEUE_URL=$$(cd infra/opentofu && tofu output -raw sqs_default_queue_url) >> llm-gateway/.env.localstack
	@echo SQS_PRIORITY_QUEUE_URL=$$(cd infra/opentofu && tofu output -raw sqs_priority_queue_url) >> llm-gateway/.env.localstack
	@echo "[infra] Done. Source llm-gateway/.env.localstack to export variables."

infra-down:
	@echo "[infra] Destroying OpenTofu stack"
	cd infra/opentofu && tofu destroy -auto-approve || true

infra-env:
	@echo "export AWS_REGION=us-east-1"
	@echo "export AWS_ACCESS_KEY_ID=test"
	@echo "export AWS_SECRET_ACCESS_KEY=test"
	@echo "export SQS_ENDPOINT_URL=http://localhost:4566"
	@echo "export DYNAMODB_ENDPOINT_URL=http://localhost:8000"
	@echo "export DDB_TABLE=Conversations"
	@echo "export SQS_QUEUE_URL=$$(cd infra/opentofu && tofu output -raw sqs_default_queue_url)"
	@echo "export SQS_PRIORITY_QUEUE_URL=$$(cd infra/opentofu && tofu output -raw sqs_priority_queue_url)"
	$(DOCKER_COMPOSE) up --build -d
	$(DOCKER_COMPOSE) start

