/*
Generated by GitHub Copilot (OpenAI model)
Description: Minimal test script for routing logic. No framework; prints PASS/FAIL and exits with non-zero on failure.
Context: Validates that image signals route to Ollama, text-only to vLLM.
*/

const { decideRoute } = require('../src/shared/routing');

function assertEqual(name, a, b) {
  if (a !== b) {
    console.error(`FAIL: ${name}: expected ${b}, got ${a}`);
    process.exitCode = 1;
  } else {
    console.log(`PASS: ${name}`);
  }
}

assertEqual('text-only -> vllm', decideRoute({ user_message: 'hello there' }), 'vllm');
assertEqual('image_url field -> ollama', decideRoute({ user_message: 'caption', image_url: 'http://x/cat.png' }), 'ollama');
assertEqual('images array -> ollama', decideRoute({ user_message: 'caption', images: [{ image_url: 'http://x/dog.jpg' }] }), 'ollama');

if (process.exitCode) {
  process.exit(process.exitCode);
}
