# Generated by Copilot (OpenAI)
# Description: OpenTofu configuration to provision local AWS-equivalent infra for the LLM Gateway.
# - Optionally runs LocalStack and DynamoDB Local containers (toggle via var.start_local_containers)
# - Provisions SQS queues on LocalStack and a DynamoDB table on DynamoDB Local
# - Includes commented-out examples for real AWS deployment syntax

locals {
  # Convenience flags
  ls_enabled   = var.start_local_containers
}

# --- Optional: start LocalStack and DynamoDB Local containers -----------------
resource "docker_image" "localstack" {
  count = local.ls_enabled ? 1 : 0
  name  = "localstack/localstack:latest"
  keep_locally = true
}

resource "docker_container" "localstack" {
  count = local.ls_enabled ? 1 : 0
  name  = "localstack"
  image = docker_image.localstack[0].image_id
  ports {
    internal = 4566
    external = 4566
  }
  env = [
    "SERVICES=sqs,apigateway,apigatewayv2,iam,sts,logs,cloudwatch,s3",
    "DEBUG=1"
  ]
  restart = "unless-stopped"
}

resource "docker_image" "ddb_local" {
  count = local.ls_enabled ? 1 : 0
  name  = "amazon/dynamodb-local:latest"
  keep_locally = true
}

resource "docker_container" "ddb_local" {
  count = local.ls_enabled ? 1 : 0
  name  = "dynamodb-local"
  image = docker_image.ddb_local[0].image_id
  ports {
    internal = 8000
    external = 8000
  }
  restart = "unless-stopped"
}

# --- Local resources: SQS queues in LocalStack --------------------------------
resource "aws_sqs_queue" "default" {
  provider = aws.localstack
  name     = var.queue_name_default
}

resource "aws_sqs_queue" "priority" {
  provider = aws.localstack
  name     = var.queue_name_priority
}

# --- Local resource: DynamoDB table in DynamoDB Local -------------------------
resource "aws_dynamodb_table" "conversations" {
  provider       = aws.dynamodb
  name           = var.ddb_table_name
  billing_mode   = "PAY_PER_REQUEST"
  hash_key       = "conversation_id"

  attribute {
    name = "conversation_id"
    type = "S"
  }
}

# --- Outputs for local dev wiring --------------------------------------------
output "sqs_default_queue_url" {
  value = aws_sqs_queue.default.url
}

output "sqs_priority_queue_url" {
  value = aws_sqs_queue.priority.url
}

output "dynamodb_endpoint" {
  value = var.dynamodb_local_endpoint
}

output "localstack_endpoint" {
  value = var.localstack_endpoint
}

# --- Example: Real AWS deployment (commented out) -----------------------------
# provider "aws" {
#   region = var.aws_region
# }
#
# resource "aws_sqs_queue" "default_prod" {
#   name = var.queue_name_default
# }
#
# resource "aws_sqs_queue" "priority_prod" {
#   name = var.queue_name_priority
# }
#
# resource "aws_dynamodb_table" "conversations_prod" {
#   name         = var.ddb_table_name
#   billing_mode = "PAY_PER_REQUEST"
#   hash_key     = "conversation_id"
#   attribute { name = "conversation_id" type = "S" }
# }
#
# # Optionally: API Gateway + Lambda wiring for production
# # resource "aws_lambda_function" "api_handler" { ... }
# # resource "aws_apigatewayv2_api" "http_api" { ... }
# # resource "aws_apigatewayv2_integration" "lambda_integration" { ... }
# # resource "aws_apigatewayv2_route" "chat_route" { ... }

# --- Optional: API Gateway in LocalStack to proxy to local Express -------------
resource "aws_apigatewayv2_api" "llm_api" {
  provider     = aws.localstack
  count        = var.enable_apigw ? 1 : 0
  name         = "llm-gateway-http-api"
  protocol_type = "HTTP"
}

resource "aws_apigatewayv2_integration" "proxy_integration" {
  provider                = aws.localstack
  count                   = var.enable_apigw ? 1 : 0
  api_id                  = aws_apigatewayv2_api.llm_api[0].id
  integration_type        = "HTTP_PROXY"
  integration_method      = "ANY"
  integration_uri         = var.local_api_base_url
  payload_format_version  = "2.0"
}

resource "aws_apigatewayv2_route" "$default" {
  provider = aws.localstack
  count    = var.enable_apigw ? 1 : 0
  api_id   = aws_apigatewayv2_api.llm_api[0].id
  route_key = "$default"
  target    = "integrations/${aws_apigatewayv2_integration.proxy_integration[0].id}"
}

resource "aws_apigatewayv2_stage" "dev" {
  provider    = aws.localstack
  count       = var.enable_apigw ? 1 : 0
  api_id      = aws_apigatewayv2_api.llm_api[0].id
  name        = var.apigw_stage_name
  auto_deploy = true
}
