# Generated by Copilot (OpenAI) — OpenTofu providers for LocalStack, DynamoDB Local, and Docker
# Purpose: Provision local AWS-equivalent services and their containers for development.

terraform {
  required_version = ">= 1.6.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0"
    }
    docker = {
      source  = "kreuzwerker/docker"
      version = ">= 3.0"
    }
  }
}

# Docker provider to run local service containers
provider "docker" {}

# LocalStack provider (for SQS, API Gateway, IAM, etc.)
provider "aws" {
  alias   = "localstack"
  region  = var.aws_region
  access_key = var.aws_access_key
  secret_key = var.aws_secret_key

  skip_credentials_validation = true
  skip_metadata_api_check     = true
  s3_use_path_style           = true

  endpoints {
    apigateway  = var.localstack_endpoint
    apigatewayv2= var.localstack_endpoint
    cloudwatch  = var.localstack_endpoint
    dynamodb    = var.localstack_endpoint
    iam         = var.localstack_endpoint
    lambda      = var.localstack_endpoint
    logs        = var.localstack_endpoint
    s3          = var.localstack_endpoint
    ses         = var.localstack_endpoint
    sns         = var.localstack_endpoint
    sqs         = var.localstack_endpoint
    ssm         = var.localstack_endpoint
    sts         = var.localstack_endpoint
  }
}

# Dedicated provider for DynamoDB Local (amazon/dynamodb-local container)
provider "aws" {
  alias   = "dynamodb"
  region  = var.aws_region
  access_key = var.aws_access_key
  secret_key = var.aws_secret_key

  skip_credentials_validation = true
  skip_metadata_api_check     = true

  endpoints {
    dynamodb = var.dynamodb_local_endpoint
  }
}
