# Generated by Copilot (OpenAI) — Inputs for OpenTofu local stack

variable "aws_region" {
  description = "AWS region for LocalStack and DynamoDB Local"
  type        = string
  default     = "us-east-1"
}

variable "aws_access_key" {
  description = "Fake access key for local emulators"
  type        = string
  default     = "test"
}

variable "aws_secret_key" {
  description = "Fake secret key for local emulators"
  type        = string
  default     = "test"
}

variable "localstack_endpoint" {
  description = "LocalStack edge endpoint URL"
  type        = string
  default     = "http://localhost:4566"
}

variable "dynamodb_local_endpoint" {
  description = "DynamoDB Local endpoint URL"
  type        = string
  default     = "http://localhost:8000"
}

variable "ddb_table_name" {
  description = "DynamoDB table name for conversation history"
  type        = string
  default     = "Conversations"
}

variable "queue_name_default" {
  description = "Default SQS queue name"
  type        = string
  default     = "llm-default-queue"
}

variable "queue_name_priority" {
  description = "Priority SQS queue name"
  type        = string
  default     = "llm-priority-queue"
}

variable "start_local_containers" {
  description = "Whether to start LocalStack and DynamoDB Local via Docker provider"
  type        = bool
  default     = true
}
