/*
Generated by GitHub Copilot (OpenAI model)
Description: Unit test for handler POST /chat enqueuing to SQS on LocalStack.
*/

const { SQSClient, CreateQueueCommand, GetQueueUrlCommand, ReceiveMessageCommand, PurgeQueueCommand } = require('@aws-sdk/client-sqs');

async function ensureQueue(sqs, name) {
  await sqs.send(new CreateQueueCommand({ QueueName: name }).catch(async () => {
    const url = await sqs.send(new GetQueueUrlCommand({ QueueName: name }));
    return url;
  }));
  const out = await sqs.send(new GetQueueUrlCommand({ QueueName: name }));
  return out.QueueUrl;
}

async function run() {
  process.env.AWS_REGION = process.env.AWS_REGION || 'us-east-1';
  process.env.AWS_ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID || 'test';
  process.env.AWS_SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY || 'test';
  process.env.SQS_ENDPOINT_URL = process.env.SQS_ENDPOINT_URL || 'http://localhost:4566';
  process.env.DYNAMODB_ENDPOINT_URL = process.env.DYNAMODB_ENDPOINT_URL || 'http://localhost:8000';
  process.env.DDB_TABLE = process.env.DDB_TABLE || 'Conversations';

  const sqs = new SQSClient({ region: process.env.AWS_REGION, endpoint: process.env.SQS_ENDPOINT_URL, credentials: { accessKeyId: 'test', secretAccessKey: 'test' } });
  const qName = 'llm-default-queue-test';
  const qUrl = await ensureQueue(sqs, qName);
  // Purge any existing messages
  await sqs.send(new PurgeQueueCommand({ QueueUrl: qUrl }).catch(() => undefined));

  process.env.SQS_QUEUE_URL = qUrl;

  const { handler } = require('../src/middleware/handler');

  const event = {
    version: '2.0',
    requestContext: { http: { method: 'POST', path: '/chat' } },
    rawPath: '/chat',
    body: JSON.stringify({ conversation_id: 'conv-enq-1', user_message: 'Hello world' }),
  };

  const res = await handler(event);
  if (res.statusCode !== 202) { console.error('FAIL: handler status', res.statusCode, res.body); process.exit(1); }

  const recv = await sqs.send(new ReceiveMessageCommand({ QueueUrl: qUrl, MaxNumberOfMessages: 1, WaitTimeSeconds: 2 }));
  const msg = recv.Messages && recv.Messages[0];
  if (!msg) { console.error('FAIL: no message enqueued'); process.exit(1); }
  const body = JSON.parse(msg.Body);
  if (body.conversation_id !== 'conv-enq-1') { console.error('FAIL: message body mismatch'); process.exit(1); }

  console.log('PASS: handler enqueued message');
}

run().catch(err => { console.error('FAIL:', err.message); process.exit(1); });
