/*
Generated by GitHub Copilot (OpenAI model)
Description: Unit test for historyStore against DynamoDB Local. Creates table if missing, then exercises ensure/get/append.
*/

const { DynamoDBClient, CreateTableCommand, DescribeTableCommand } = require('@aws-sdk/client-dynamodb');

async function ensureTable(ddb, tableName) {
  try {
    await ddb.send(new DescribeTableCommand({ TableName: tableName }));
    return;
  } catch (_) {}
  await ddb.send(new CreateTableCommand({
    TableName: tableName,
    BillingMode: 'PAY_PER_REQUEST',
    AttributeDefinitions: [{ AttributeName: 'conversation_id', AttributeType: 'S' }],
    KeySchema: [{ AttributeName: 'conversation_id', KeyType: 'HASH' }],
  }));
}

async function run() {
  process.env.AWS_REGION = process.env.AWS_REGION || 'us-east-1';
  process.env.AWS_ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID || 'test';
  process.env.AWS_SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY || 'test';
  process.env.DYNAMODB_ENDPOINT_URL = process.env.DYNAMODB_ENDPOINT_URL || 'http://localhost:8000';
  process.env.DDB_TABLE = process.env.DDB_TABLE || 'Conversations';

  const ddb = new DynamoDBClient({ region: process.env.AWS_REGION, endpoint: process.env.DYNAMODB_ENDPOINT_URL, credentials: { accessKeyId: 'test', secretAccessKey: 'test' } });
  await ensureTable(ddb, process.env.DDB_TABLE);

  const store = require('../src/shared/historyStore');

  const id = 'conv-hist-1';
  await store.ensureConversation(id);
  const before = await store.getConversation(id);
  if (!before || before.conversation_id !== id) { console.error('FAIL: getConversation initial'); process.exit(1); }

  await store.appendMessages(id, [
    { role: 'user', content: 'hello' },
    { role: 'assistant', content: 'hi there' },
  ]);

  const after = await store.getConversation(id);
  if (!Array.isArray(after.messages) || after.messages.length !== 2) {
    console.error('FAIL: appendMessages did not persist 2 messages');
    process.exit(1);
  }
  console.log('PASS: historyStore ensure/get/append');
}

run().catch(err => { console.error('FAIL:', err.message); process.exit(1); });
