/*
Generated by GitHub Copilot (OpenAI model)
Description: Shared AWS SDK v3 clients for DynamoDB and SQS with environment-driven endpoints for Moto local emulation. Provides configured clients reused across middleware and worker.
Context: Used by src/shared/historyStore.js, src/middleware/handler.js, src/worker/worker.js
*/

const { DynamoDBClient } = require('@aws-sdk/client-dynamodb');
const { DynamoDBDocumentClient } = require('@aws-sdk/lib-dynamodb');
const { SQSClient } = require('@aws-sdk/client-sqs');

const REGION = process.env.AWS_REGION || 'us-east-1';
const DYNAMODB_ENDPOINT_URL = process.env.DYNAMODB_ENDPOINT_URL || undefined;
const SQS_ENDPOINT_URL = process.env.SQS_ENDPOINT_URL || undefined;

// Basic credentials defaults for local emulators like Moto
const credentials = process.env.AWS_ACCESS_KEY_ID && process.env.AWS_SECRET_ACCESS_KEY
  ? {
      accessKeyId: process.env.AWS_ACCESS_KEY_ID,
      secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
      sessionToken: process.env.AWS_SESSION_TOKEN,
    }
  : undefined;

function createDynamoDocClient() {
  const ddb = new DynamoDBClient({ region: REGION, endpoint: DYNAMODB_ENDPOINT_URL, credentials });
  return DynamoDBDocumentClient.from(ddb, {
    marshallOptions: { removeUndefinedValues: true },
    unmarshallOptions: { wrapNumbers: false },
  });
}

function createSqsClient() {
  return new SQSClient({ region: REGION, endpoint: SQS_ENDPOINT_URL, credentials });
}

module.exports = {
  createDynamoDocClient,
  createSqsClient,
};
