/*
Generated by GitHub Copilot (OpenAI model)
Description: Conversation history persistence in DynamoDB. Fetch by conversation_id and append messages atomically.
Context: Used by middleware to read history and worker to append user+assistant messages.
*/

const { GetCommand, UpdateCommand, PutCommand } = require('@aws-sdk/lib-dynamodb');
const { createDynamoDocClient } = require('./aws');

const TABLE = process.env.DDB_TABLE || 'Conversations';
const ddb = createDynamoDocClient();

async function getConversation(conversationId) {
  if (!conversationId) throw new Error('conversation_id required');
  const res = await ddb.send(new GetCommand({
    TableName: TABLE,
    Key: { conversation_id: conversationId },
  }));
  if (!res.Item) {
    return { conversation_id: conversationId, messages: [], updated_at: new Date().toISOString() };
  }
  // Ensure shape
  res.Item.messages = Array.isArray(res.Item.messages) ? res.Item.messages : [];
  return res.Item;
}

async function appendMessages(conversationId, newMessages) {
  if (!conversationId) throw new Error('conversation_id required');
  const ts = new Date().toISOString();
  const params = {
    TableName: TABLE,
    Key: { conversation_id: conversationId },
    UpdateExpression: 'SET messages = list_append(if_not_exists(messages, :empty), :msgs), updated_at = :ts',
    ExpressionAttributeValues: {
      ':empty': [],
      ':msgs': newMessages || [],
      ':ts': ts,
    },
    ReturnValues: 'ALL_NEW',
  };
  const out = await ddb.send(new UpdateCommand(params));
  return out.Attributes;
}

async function ensureConversation(conversationId) {
  // Create a stub item if doesn't exist, to avoid first append surprises in some emulators
  const now = new Date().toISOString();
  await ddb.send(new PutCommand({
    TableName: TABLE,
    Item: { conversation_id: conversationId, messages: [], updated_at: now },
    ConditionExpression: 'attribute_not_exists(conversation_id)',
  }).catch(() => undefined));
}

module.exports = {
  getConversation,
  appendMessages,
  ensureConversation,
};
