/*
Generated by GitHub Copilot (OpenAI model)
Description: Shared LLM calling functions for vLLM and Ollama via OpenAI-compatible API.
Context: Used by middleware for sync chat and by worker for async.
*/

const axios = require('axios');

const VLLM_BASE_URL = process.env.VLLM_BASE_URL || 'http://localhost:8000';
const VLLM_MODEL = process.env.VLLM_MODEL || 'llama-3-8b-instruct';

const OLLAMA_OPENAI_BASE_URL = process.env.OLLAMA_OPENAI_BASE_URL || process.env.OLLAMA_BASE_URL || 'http://localhost:11434';
const OLLAMA_MODEL = process.env.OLLAMA_MODEL || 'llava:13b';

function toOpenAIMessages(history, userMessage, images) {
  const msgs = (history || []).map(m => ({ role: m.role, content: m.content }));
  if (images && images.length > 0) {
    const content = [];
    content.push({ type: 'text', text: userMessage });
    for (const img of images) {
      const url = typeof img === 'string' ? img : (img.image_url || img.url);
      if (url) content.push({ type: 'image_url', image_url: { url } });
    }
    msgs.push({ role: 'user', content });
  } else {
    msgs.push({ role: 'user', content: userMessage });
  }
  return msgs;
}

async function callVLLM(history, userMessage) {
  const url = `${VLLM_BASE_URL.replace(/\/$/, '')}/v1/chat/completions`;
  const data = {
    model: VLLM_MODEL,
    messages: toOpenAIMessages(history, userMessage, null),
    stream: false,
    temperature: 0.3,
  };
  const r = await axios.post(url, data, { timeout: 120000 });
  const text = r.data.choices?.[0]?.message?.content || '';
  return text;
}

async function callOllama(history, userMessage, images) {
  const base = OLLAMA_OPENAI_BASE_URL.replace(/\/$/, '');
  const url = `${base}/v1/chat/completions`;
  const data = {
    model: OLLAMA_MODEL,
    messages: toOpenAIMessages(history, userMessage, images),
    stream: false,
    temperature: 0.2,
  };
  const r = await axios.post(url, data, { timeout: 180000 });
  const text = r.data.choices?.[0]?.message?.content || '';
  return text;
}

module.exports = { callVLLM, callOllama, toOpenAIMessages };
