/*
Generated by GitHub Copilot (OpenAI model)
Description: Minimal logger that writes to console and a LOGS/<PROCESS>-log-<UNIX_TIMESTAMP>.log file when a process name is provided.
Context: Used by local server and worker for debug logs.
*/

const fs = require('fs');
const path = require('path');

function createLogger(processName = 'app') {
  const logsDir = path.resolve(__dirname, '../../LOGS');
  let filePath = null;
  try {
    if (!fs.existsSync(logsDir)) fs.mkdirSync(logsDir, { recursive: true });
    const ts = Math.floor(Date.now() / 1000);
    filePath = path.join(logsDir, `${processName}-log-${ts}.log`);
  } catch (_) {
    // ignore file issues; fall back to console-only
  }

  function write(level, ...args) {
    const line = `[${new Date().toISOString()}] [${level.toUpperCase()}] ${args.map(String).join(' ')}`;
    // console
    if (level === 'error') console.error(line); else console.log(line);
    // file
    if (filePath) {
      try { fs.appendFileSync(filePath, line + '\n'); } catch (_) {}
    }
  }

  return {
    debug: (...args) => write('debug', ...args),
    info: (...args) => write('info', ...args),
    warn: (...args) => write('warn', ...args),
    error: (...args) => write('error', ...args),
  };
}

module.exports = { createLogger };
