/*
Generated by GitHub Copilot (OpenAI model)
Description: Intelligent routing helper that selects vLLM (text-only) or Ollama (multimodal) based on payload content.
Context: Used by middleware to tag jobs and by tests to validate decisions.
*/

function hasImages(payload) {
  if (!payload) return false;
  if (Array.isArray(payload.images) && payload.images.length > 0) return true;
  if (payload.image_url) return true;
  if (typeof payload.user_message === 'string') {
    // naive URL heuristic
    const urlRegex = /(https?:\/\/\S+\.(png|jpg|jpeg|gif|webp))/i;
    if (urlRegex.test(payload.user_message)) return true;
  }
  return false;
}

function decideRoute(payload) {
  return hasImages(payload) ? 'ollama' : 'vllm';
}

module.exports = { decideRoute, hasImages };
